version: "3"
services:
  frontend:
    image: ksoon1985/docker-frontend  
    volumes: 
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m 
    
  nginx:
    restart: always
    image: ksoon1985/docker-nginx
    ports:
      - "80:80" 
    mem_limit: 128m
    links:
      - frontend
      - backend
    
  backend:
    image: ksoon1985/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    mem_limit: 128m
    environment: 
      - MYSQL_HOST: $MYSQL_HOST
      - MYSQL_USER: $MYSQL_USER
      - MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD 
      - MYSQL_DATABASE: $MYSQL_DATABASE
      - MYSQL_PORT: $MYSQL_PORT
    
